version: '2'
services:
    csensing-app:
        image: csensing
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://csensing-postgresql:5432/csensing
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    csensing-postgresql:
        extends:
            file: postgresql.yml
            service: csensing-postgresql
