version: '2'
services:
    csensing-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/csensing/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=csensing
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
